-- require('quarto').setup {
--     debug = false,
--     closePreviewOnExit = true,
--     lspFeatures = {
--         enabled = true,
--         chunks = "curly",
--         languages = { "r", "python", "julia", "bash", "html" },
--         diagnostics = {
--             enabled = true,
--             triggers = { "BufWritePost" },
--         },
--         completion = {
--             enabled = true,
--         },
--     },
--     codeRunner = {
--         enabled = true,
--         default_method = "molten", -- "molten", "slime", "iron" or <function>
--         ft_runners = {},           -- filetype to runner, ie. `{ python = "molten" }`.
--         -- Takes precedence over `default_method`
--         never_run = { 'yaml' },    -- filetypes which are never sent to a code runner
--     },
-- }
-- runner = require("quarto.runner")
-- vim.keymap.set("n", "<leader>rc", runner.run_cell)
-- vim.keymap.set("n", "<leader>rA", function() runner.run_all(true) end)

-- vim.api.nvim_create_autocmd("FileType", {
--     pattern = "markdown",
--     callback = function()
--         require("quarto").activate()
--     end,
-- })
