# Gruvbox Material Hard theme
# Adapted from provided image colors
# Licensed under the MIT license

# two numbers, legacy, platform
text_composition_strategy legacy

background_opacity 0.4
background_blur 10
background  #141617
foreground  #ddc7a1

cursor                #928374

selection_foreground  #928374
selection_background  #3c3836

color0  #282828
color8  #928374

# red
color1                #ea6962
# light red
color9                #f07560

# green
color2                #a9b665
# light green
color10               #b8bb26

# yellow
color3                #d8a657
# light yellow
color11               #fabc59

# blue
color4                #7daea3
# light blue
color12               #89dceb

# magenta (purple)
color5                #d3869b
# light magenta
color13               #f38ba8

# cyan (aqua)
color6                #89b482
# light cyan
color14               #a9d8c2

# light gray
color7                #a89984
# dark gray
color15               #928374

